apiVersion: okta.jet.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: okta-default
spec:
  credentials:
    source: Secret
    secretRef:
      name: okta-default-creds
      namespace: crossplane-system
      key: credentials
