apiVersion: app.okta.jet.crossplane.io/v1alpha2
kind: Oauth
metadata:
  name: okta-oauth-app-example
spec:
  forProvider:
    label: "okta-oauth-app-example"
    type: "web"
    grantTypes: ["authorization_code", "refresh_token"]
    responseTypes: ["code"]
    redirectUris: ["myapp://callback", "myapp://callback2"]
    userNameTemplate: "$${source.login}"
  providerConfigRef:
    name: okta-default
  writeConnectionSecretToRef:
    name: okta-oauth-app-example
    namespace: crossplane-system
